# custom tag that will be added to all saved df's and models. 
# useful if you are training say ggH classifier and want to save dataframe with ggH preselection. 
# otherwise may get confused when training another clf like VBF 
output_tag:
    'ggH_BDT'

#Higgs boson mass to pick up norms from!
mH:
  '125'

#.root MC files for all years (sig and bkg) should be kept in this dir:
mc_file_dir:
    '/vols/cms/jwd18/HToEESamples/MC/'

#.root Data files for all years should be kept in this dir:
data_file_dir:
    '/vols/cms/jwd18/HToEESamples/Data/'

mc_file_names:
    sig:
        ggH:
            '2016A': 'ggH_UL2016A.root'
            '2016B': 'ggH_UL2016B.root'
            '2017': 'ggH_UL2017.root'
            '2018': 'ggH_UL2018.root'
        #ggHDalitz:
        #    #'2016A': 'ggHDalitz_UL2017.root'
        #    #'2016B': 'ggHDalitz_UL2017.root'
        #    '2017':  'ggHDalitz_UL2017.root'
        #    #'2018':  'ggHDalitz_UL2017.root'
        #VBFDalitz:
        #    #'2016A': 'ggHDalitz_UL2017.root'
        #    #'2016B': 'ggHDalitz_UL2017.root'
        #    '2017':  'VBFDalitz_UL2017.root'
        #    #'2018':  'ggHDalitz_UL2017.root'
        #VBF: #FOR PLOTTING ONLY (not training to reject this)
        #    '2016A': 'VBF_UL2016A.root'
        #    '2016B': 'VBF_UL2016B.root'
        #    '2017': 'VBF_UL2017.root'
        #    '2018': 'VBF_UL2018.root'
    bkg:
        DYMC:
            '2016A': 'DY_UL2016A.root'
            '2016B': 'DY_UL2016B.root'
            '2017': 'DY_UL2017.root'
            '2018': 'DY_UL2018.root'

        TT2L2Nu:
            '2016A': 'TTLNu_UL2016A.root'
            '2016B': 'TTLNu_UL2016B.root'
            '2017': 'TTLNu_UL2017.root'
            '2018': 'TTLNu_UL2018.root'
        TTSemiL:
            '2016A': 'TTSemi_UL2016A.root'
            '2016B': 'TTSemi_UL2016B.root'
            '2017': 'TTSemi_UL2017.root'
            '2018': 'TTSemi_UL2018.root'

data_file_names:
    Data:
        '2016A': 'Data_UL2016A.root'
        '2016B': 'Data_UL2016B.root'
        '2017': 'Data_UL2017.root'
        '2018': 'Data_UL2018.root'

#.root MC files for all years (bkg) should have these tree path:
proc_to_tree_name:
    ggH: 'Events'
    VBF: 'Events'
    ggHDalitz: 'Events'
    VBFDalitz: 'Events'
    DYMC: 'Events'
    Data: 'Events'
    TT2L2Nu: 'Events'
    TTSemiL: 'Events'

#X variables to train with. Must be in nominal_vars (unless created from existing features)
train_vars:
#matching ggh_dnn vars
    ['dielectronPt','dielectronCosPhi',      
     'leadElectronPtOvM', 'subleadElectronPtOvM',
     'leadElectronEta', 'subleadElectronEta',
     'dijetAbsDEta', 'dijetDPhi','dijetMinDRJetEle', 'dijetMass', 
     'dijetDieleAbsDPhiTrunc', 'dijetDieleAbsDEta', 'dijetCentrality',
     'leadJetDieleDPhi', 'subleadJetDieleDPhi', 'leadJetDieleDEta', 'subleadJetDieleDEta',
     'leadJetEn', 'leadJetPt','leadJetEta', 'leadJetPhi','leadJetQGL', 
     'subleadJetEn', 'subleadJetPt', 'subleadJetEta', 'subleadJetPhi','subleadJetQGL',
     #'n_jets'
     #'eMinusDielectronDThetaLab'
     #'leadJetPUJID','subleadJetPUJID', 'subsubleadJetPUJID','leadJetID','subleadJetID','subsubleadJetID'
     #'metSumET', 'metPt', 'metPhi', 'leadJetBTagScore', 'subleadJetBTagScore', 'subsubleadJetBTagScore'
    ]

vars_to_add:
    #'eMinusDielectronDThetaLab': 
    #'n_jets': 
    

#preselection that will be applied to all samples
preselection:
    'dielectronMass > 110 and dielectronMass < 150 and leadElectronPtOvM > 0.333 and subleadElectronPtOvM > 0.25 and (leadElectronCharge == -subleadElectronCharge)' 

#need looser cut for re-weighting around Z mass. Actual CR selection is defined is DataHandling.py
reweight_cr:
    'dielectronMass > 80 and dielectronMass < 150 and leadElectronPtOvM > 0.333 and subleadElectronPtOvM > 0.25 and (leadElectronCharge == -subleadElectronCharge)' 
