# custom tag that will be added to all saved df's and models. 
output_tag:
    'VBF_DNN'

#Higgs boson mass to pick up norms from!
mH:
  '125'

#.root MC files for all years (sig and bkg) should be kept in this dir:
mc_file_dir:
    '/vols/cms/jwd18/HToEESamples/MC/'

#.root Data files for all years should be kept in this dir:
data_file_dir:
    '/vols/cms/jwd18/HToEESamples/Data/'

mc_file_names:
    sig:
        VBF:
            '2016A': 'VBF_UL2016A.root'
            '2016B': 'VBF_UL2016B.root'
            '2017': 'VBF_UL2017.root'
            '2018': 'VBF_UL2018.root'
    bkg:
        DYMC:
            '2016A': 'DY_UL2016A.root'
            '2016B': 'DY_UL2016B.root'
            '2017': 'DY_UL2017.root' 
            '2018': 'DY_UL2018.root'
        TT2L2Nu:
            '2016A': 'TTLNu_UL2016A.root'
            '2016B': 'TTLNu_UL2016B.root'
            '2017': 'TTLNu_UL2017.root'
            '2018': 'TTLNu_UL2018.root'
        TTSemiL:
            '2016A': 'TTSemi_UL2016A.root'
            '2016B': 'TTSemi_UL2016B.root'
            '2017': 'TTSemi_UL2017.root'
            '2018': 'TTSemi_UL2018.root' 
        EWKZ:
            '2016A': 'EWKZ_2017.root' #dont have 2016 atm
            '2016B': 'EWKZ_2017.root' #dont have 2016 atm
            '2017': 'EWKZ_2017.root'
            '2018': 'EWKZ_2018.root'

data_file_names:
    Data:
        '2016A': 'Data_UL2016A.root'
        '2016B': 'Data_UL2016B.root'
        '2017': 'Data_UL2017.root'
        '2018': 'Data_UL2018.root'

#.root files for all years should have these tree paths. Keys should match keys above
proc_to_tree_name:
    VBF: 'Events'
    DYMC: 'Events'
    Data: 'Events'
    TT2L2Nu: 'Events'
    TTSemiL: 'Events'
    EWKZ: 'Events'

#X variables to train with (4 vectors of jets... and maybe photons... anything else that is low-level and maybe useful?)
object_vars:
    [['leadJetEn', 'leadJetPt', 'leadJetEta', 'leadJetPhi','leadJetQGL'], 
     ['subleadJetEn', 'subleadJetPt', 'subleadJetEta', 'subleadJetPhi','subleadJetQGL'],
     ['subsubleadJetEn', 'subsubleadJetPt', 'subsubleadJetEta', 'subsubleadJetPhi', 'subsubleadJetQGL']
    ]

event_vars:
    ['dijetAbsDEta', 'dijetDPhi','dijetMinDRJetEle', 'dijetMass', 
     'dijetDieleAbsDPhiTrunc', 'dijetDieleAbsDEta', 'dijetCentrality',
     'leadJetDieleDPhi', 'leadJetDieleDEta', 'subleadJetDieleDPhi', 'subleadJetDieleDEta',
     'leadElectronPtOvM', 'subleadElectronPtOvM', 'dielectronPt'
    ]

train_vars: #all vars for plotting inputs. Can just get this from above vars
    ['dijetAbsDEta', 'dijetDPhi','dijetMinDRJetEle', 'dijetMass', 
     'dijetDieleAbsDPhiTrunc', 'dijetDieleAbsDEta', 'dijetCentrality',
     'leadJetDieleDPhi', 'leadJetDieleDEta', 'subleadJetDieleDPhi', 'subleadJetDieleDEta',
     'leadElectronPtOvM', 'subleadElectronPtOvM', 'dielectronPt',
     'leadJetEn', 'leadJetPt', 'leadJetEta', 'leadJetPhi','leadJetQGL', 
     'subleadJetEn', 'subleadJetPt', 'subleadJetEta', 'subleadJetPhi','subleadJetQGL',
     'subsubleadJetEn', 'subsubleadJetPt', 'subsubleadJetEta', 'subsubleadJetPhi', 'subsubleadJetQGL'
    ] 

vars_to_add:

#preselection that will be applied to all samples
preselection:
    'dielectronMass > 110 and dielectronMass < 150 and leadElectronPtOvM > 0.333 and subleadElectronPtOvM > 0.25 and dijetMass>250 and leadJetPt>40 and subleadJetPt>30'
