models:
    VBF: 'VBF_BDT_clf.pickle.dat'
    ggH: 'ggH_BDT_pt_reweighted_clf.pickle.dat'

#boundaries: #pass24
#    VBF: 
#        tag_0: 0.922
#        tag_1: 0.783
#    ggH:
#        tag_0: 0.856
#        tag_1: 0.680
#        tag_2: 0.481
#        tag_3: 0.229

boundaries: #pass25
    VBF: 
        tag_0: 0.910
        tag_1: 0.776
    ggH:
        tag_0: 0.834
        tag_1: 0.700
        tag_2: 0.556
        tag_3: 0.246
